version: "3.9"

services:
  supplier-service:
    build:
      context: . # assumes Dockerfile is in the same directory
      dockerfile: Dockerfile
    container_name: supplier-service
    restart: always

    env_file:
      - supplier.env

    ports:
      - "${PORT:-3001}:3001"

    depends_on: [] # no need to start other services; they already exist

    networks:
      - ea2sa-net
      - ea2sa-erp-phoenix # so it can reach the database (northwind_erp)
      - supplier-service_ea2sa-net
      - product-service_ea2sa-net
      - order_ea2sa-net

# External networks (must already exist)
networks:
  ea2sa-net:
    external: true
  ea2sa-erp-phoenix:
    external: true
  supplier-service_ea2sa-net:
    external: true
  product-service_ea2sa-net:
    external: true
  order_ea2sa-net:
    external: true
